#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Oct 31 15:39:14 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade




class Ventana4(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana4.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 330))
        self.SetTitle("frame_3")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./BOLETOS.jfif", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbTiquet = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        lbTiquet.SetForegroundColour(wx.Colour(35, 142, 35))
        lbTiquet.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_1.Add(lbTiquet, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./BOLETOS.jfif", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetForegroundColour(wx.Colour(35, 142, 35))
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_1.Add(label_1, 0, wx.EXPAND, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTaquilla.SetForegroundColour(wx.Colour(60, 60, 243))
        lbTaquilla.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(lbTaquilla, 0, wx.EXPAND, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        lbSubtotalTaquilla.SetForegroundColour(wx.Colour(0, 127, 255))
        lbSubtotalTaquilla.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Britannic Bold"))
        sizer_1.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetForegroundColour(wx.Colour(35, 142, 35))
        label_5.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_1.Add(label_5, 0, wx.EXPAND, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "---", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbDulceria.SetForegroundColour(wx.Colour(60, 60, 246))
        lbDulceria.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(lbDulceria, 0, wx.EXPAND, 0)

        lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        lbSubtotalDulceria.SetForegroundColour(wx.Colour(0, 127, 255))
        lbSubtotalDulceria.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Britannic Bold"))
        sizer_1.Add(lbSubtotalDulceria, 0, 0, 0)

        lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, "TOTAL: $")
        lbTotal.SetForegroundColour(wx.Colour(255, 0, 0))
        lbTotal.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_1.Add(lbTotal, 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "CANCELAR")
        self.btnCancelar.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.btnCancelar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_2.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "FINALIZAR")
        self.btnFinalizar.SetBackgroundColour(wx.Colour(82, 164, 0))
        self.btnFinalizar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnFinalizar.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_2.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        print("Event handler 'cancelarVenta' not implemented!")
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        print("Event handler 'finalizarVenta' not implemented!")
        event.Skip()

# end of class Ventana4
class Ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        # begin wxGlade: Ventana3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((878, 628))
        self.SetTitle("frame_2")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Dulcess.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_4.SetMinSize((100, 92))
        grid_sizer_1.Add(bitmap_4, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetForegroundColour(wx.Colour(35, 142, 35))
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Dulcess.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_5.SetMinSize((100, 92))
        grid_sizer_1.Add(bitmap_5, 0, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(1, 6, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_2.Add(self.spComboB, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        label_2.SetForegroundColour(wx.Colour(35, 142, 35))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch\nRefresco ch")
        label_3.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_3.Add(label_3, 0, 0, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./comboclasico.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((100, 92))
        grid_sizer_2.Add(bitmap_1, 0, 0, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_2.Add(self.spComboC, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        label_4.SetForegroundColour(wx.Colour(35, 142, 35))
        label_4.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_4.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Md\n2 Refrescos  Md")
        label_5.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_4.Add(label_5, 0, 0, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./comboCuates.png", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((100, 92))
        grid_sizer_2.Add(bitmap_2, 0, 0, 0)

        grid_sizer_5 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_5.Add(self.spComboF, 0, 0, 0)

        grid_sizer_6 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        label_6.SetForegroundColour(wx.Colour(35, 142, 35))
        label_6.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_6.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Gr\n3 Refrescos Gr\n1 Dulce")
        label_7.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_6.Add(label_7, 0, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combofamiliar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(bitmap_3, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Palomitas.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_6.SetMinSize((100, 92))
        grid_sizer_8.Add(bitmap_6, 0, 0, 0)

        grid_sizer_9 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_8.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_9.Add(label_8, 0, 0, 0)

        grid_sizer_10 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.spChicas = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_10.Add(self.spChicas, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        label_9.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_10.Add(label_9, 0, 0, 0)

        self.spMedianas = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_10.Add(self.spMedianas, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        label_10.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_10.Add(label_10, 0, 0, 0)

        self.spGrandes = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_10.Add(self.spGrandes, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        label_11.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_10.Add(label_11, 0, 0, 0)

        grid_sizer_11 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Refresco.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_7.SetMinSize((100, 92))
        grid_sizer_11.Add(bitmap_7, 0, 0, 0)

        grid_sizer_12 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_12.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_12.Add(label_12, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(2, 3, 0, 0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamayo:")
        label_13.SetMinSize((68, 28))
        label_13.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_13.Add(label_13, 0, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor:")
        label_14.SetMinSize((68, 28))
        label_14.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_13.Add(label_14, 0, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad:")
        label_15.SetMinSize((100, 16))
        label_15.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_13.Add(label_15, 0, 0, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Grande", "Mediano", "Chico"], style=wx.CB_DROPDOWN)
        self.cmbTamano.SetMinSize((68, 23))
        grid_sizer_13.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Sprit", "fanta", "coca_cola"], style=wx.CB_DROPDOWN)
        self.cmbSabor.SetMinSize((68, 23))
        grid_sizer_13.Add(self.cmbSabor, 0, 0, 0)

        grid_sizer_14 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_13.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCantidad.SetMinSize((45, 23))
        grid_sizer_14.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "AGREGAR")
        self.btnAgregar.SetMinSize((55, 23))
        grid_sizer_14.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_15 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        grid_sizer_16 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_15.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "PRODUCTOS AGREGADOS:")
        label_16.SetForegroundColour(wx.Colour(35, 142, 35))
        label_16.SetFont(wx.Font(9, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        grid_sizer_16.Add(label_16, 0, wx.ALIGN_CENTER, 0)

        lbProductosagregados = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        lbProductosagregados.SetForegroundColour(wx.Colour(0, 255, 0))
        lbProductosagregados.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_16.Add(lbProductosagregados, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_17 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_15.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria:")
        label_17.SetForegroundColour(wx.Colour(35, 142, 35))
        label_17.SetFont(wx.Font(9, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        grid_sizer_17.Add(label_17, 0, wx.ALIGN_CENTER, 0)

        lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        lbSubtotal.SetMinSize((50, 16))
        lbSubtotal.SetForegroundColour(wx.Colour(255, 0, 0))
        lbSubtotal.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_17.Add(lbSubtotal, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_18 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "**LIMPIAR**")
        self.btnLimpiar.SetMinSize((108, 23))
        self.btnLimpiar.SetBackgroundColour(wx.Colour(219, 112, 147))
        self.btnLimpiar.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_18.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, ">>SIGUIENTE>>")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_18.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularCombouates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spChicas.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasch)
        self.spMedianas.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spGrandes.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.cmbTamano.Bind(wx.EVT_COMBOBOX, self.seleccionarTamano)
        self.cmbSabor.Bind(wx.EVT_COMBOBOX, self.seleccionarSabor)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria+ f"{numero} Combo Basico \n"
        self.lbProductosagregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularCombouates(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria+ f"{numero} Combo Cuates \n"
        self.lbProductosagregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*200
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria+ f"{numero} Combo Familiar \n"
        self.lbProductosagregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasch(self, event):  # wxGlade: Ventana3.<event_handler>
        print("Event handler 'calcularPalomitasch' not implemented!")
        event.Skip()

    def calcularPalomitasMd(self, event):  # wxGlade: Ventana3.<event_handler>
        print("Event handler 'calcularPalomitasMd' not implemented!")
        event.Skip()

    def calcularPalomitasG(self, event):  # wxGlade: Ventana3.<event_handler>
        print("Event handler 'calcularPalomitasG' not implemented!")
        event.Skip()

    def seleccionarTamano(self, event):  # wxGlade: Ventana3.<event_handler>
        print("Event handler 'seleccionarTamano' not implemented!")
        event.Skip()

    def seleccionarSabor(self, event):  # wxGlade: Ventana3.<event_handler>
        
        event.Skip()

    def agregarRefresco(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()
        if tamanyo == "chico":
            subtotalrefresco=numero*25
        elif tamanyo== "Mediano":
            subtotalrefresco=numero*40
        elif tamanyo=="Grande":
            subtotalrefresco=numero*60

        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbProductosagregados.SetLabel(f"${self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria+ f"{numero} Refresco: {sabor} tamaño{tamanyo}\n"
        self.lbProductosagregados.SetLabel(self.infoDulceria)
        event.Skip()
    def limpiarD(self):
        #limpiamos las variables de instancia
        self.subtotalDulceria=0
        self.infoDulceria=""

        #limbiamos los controles
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spChicas.SetValue(0)
        self.spMedianas.SetValue(0)
        self.spGrandes.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosagregados.SetLabel("---")
        self.lbSubtotal.SetLabel("$00:00")
    
    def limpiarDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmacion de Dulceria. \n"
        f"¿Estas seguro que desea adquirir?\n\n{self.infoDulceria}\n"
        f"Subtotal Dulceria: ${self.subtotalDulceria}",
        "Dulceria", style=wx.YES_NO | wx.ICON_QUESTION)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        
        if respuesta == wx.ID_YES:
            #v4
            self.limpiarD()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD()
        event.Skip()

# end of class Ventana3
class ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((350, 469))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./BOLETOS.jfif", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_RIGHT, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((160, 31))
        label_1.SetForegroundColour(wx.Colour(35, 142, 35))
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./BOLETOS.jfif", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((100, 80))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetForegroundColour(wx.Colour(35, 142, 35))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_2.Add(label_2, 0, wx.ALIGN_CENTER, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["La hora de la desaparicion", "La hermanastra fea", "Gigantes de Hierro"], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetMinSize((160, 23))
        grid_sizer_2.Add(self.cmbPelicula, 0, wx.ALIGN_CENTER, 0)

        bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./pelicula1.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmPelicula, 0, 0, 0)

        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_3.SetForegroundColour(wx.Colour(35, 142, 35))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_3.Add(label_3, 0, 0, 0)

        IbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "--------")
        IbSala.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_3.Add(IbSala, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios:")
        label_5.SetForegroundColour(wx.Colour(35, 142, 35))
        label_5.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_4.Add(label_5, 0, 0, 0)

        grid_sizer_5 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario1.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_5.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_5.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario3.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_5.Add(self.rbHorario3, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_5.Add(self.panel_2, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "BOLETOS")
        label_6.SetForegroundColour(wx.Colour(35, 142, 35))
        label_6.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_6 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos ($80):")
        label_7.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_6.Add(label_7, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_6.Add(self.tfAdultos, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores ($70):")
        label_8.SetForegroundColour(wx.Colour(35, 142, 35))
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_6.Add(self.tfMenores, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        label_9.SetForegroundColour(wx.Colour(35, 142, 35))
        sizer_1.Add(label_9, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "**Limpiar**")
        self.btnLimpiar.SetMinSize((102, 23))
        self.btnLimpiar.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_7.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, ">>Siguiente>>")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(219, 219, 112))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.selcciondeHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarmenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade
    def cargar_imagen(self,ruta):
        bitmap=wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: ventana2.<event_handler>
        pelicula =self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""
        print(f"Pelicula seleccionada: {pelicula}")
        if pelicula =="La hora de la desaparicion":
            imagen="pelicula1.jpg"
            sala="1"
            horario1="14:00"
            horario2="17:00"
            horario3="20:00"
        elif pelicula =="La hermanastra fea":
             imagen="pelicula2.jpg"
             sala="2"
             horario1="13:00"
             horario2="16:00"
             horario3="19:00"
        elif  pelicula =="Gigantes de hierro":
             imagen="pelicula3.jpg"
             sala="3"
             horario1="15:00"
             horario2="18:00"
             horario3="21:00"
        self.cargar_imagen(imagen)
        self.IbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {pelicula} \n Sala: {sala}"
        print(f"Listos para distrutar de \n {self.informacion}")
        event.Skip()

    def selcciondeHorario1(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.adultos=int(self.tfAdultos.GetValue())
            subtotal_a=self.adultos*80
            self.subtotal=subtotal_a
            self.IbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido","Error",wx.OK| wx.ICON_ERROR) 
        event.Skip()

    def sumarmenores(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.menores=int(self.tfMenores.GetValue())
            subtotal_b=self.menores*70
            self.subtotal=(self.adultos*80)+ subtotal_b
            self.IbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MenssageBox("Por favor ingresa un numero valido","Error",wx.OK| wx.ICON_ERROR)
        event.Skip()
    def limpiarValores_Campos(self):
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""
        
        self.cargar_imagen=("logo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPelicula.SetSelection(wx.NOT_FOUND)
        self.IbSala.SetLabel("---")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.IbSubtotal.SetLabel("0")
          

    def limpiarTaquilla(self, event):  # wxGlade: ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventana2.<event_handler>
        self.informacion =f"{self.informacion} \n Horario: {self.horarioSeleccionado}"
        self.informacion=f"{self.informacion} \n Adultos: {self.adultos}\n Menores de 12 años:: {self.menores}"
        self.informacion=f"{self.informacion} \n Subtotal: {self.subtotal}"
        pregunta = wx.MessageDialog(
        self,
        f"Confirmacion de Taquilla. \n"
        f"¿Estas seguro que desea adquirir?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO| wx.ICON_QUESTION
        )
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta == wx.ID_YES:
            print(f"Venta de taquilla realizada\n {self.informacion}")
            v3 = Ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            v3.show()
            self.limpiarValores_Campos()
            self.hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

# end of class ventana2

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 413))
        self.SetTitle("Inicio de secion- Cine Pluss")

        self.tbnEntrada = wx.Panel(self, wx.ID_ANY)
        self.tbnEntrada.SetBackgroundColour(wx.Colour(0, 0, 0))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        IbTitulo = wx.StaticText(self.tbnEntrada, wx.ID_ANY, "Bienvenide a cinepluss", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbTitulo.SetMinSize((132, 35))
        IbTitulo.SetForegroundColour(wx.Colour(35, 142, 35))
        IbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbTitulo, 0, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.tbnEntrada, wx.ID_ANY, wx.Bitmap("./logo.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbUsuario = wx.StaticText(self.tbnEntrada, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbUsuario.SetForegroundColour(wx.Colour(35, 142, 35))
        IbUsuario.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(IbUsuario, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.tbnEntrada, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbClave = wx.StaticText(self.tbnEntrada, wx.ID_ANY, u"Contrase�a:", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbClave.SetMinSize((64, 16))
        IbClave.SetForegroundColour(wx.Colour(35, 142, 35))
        IbClave.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(IbClave, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.tbnEntrada, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_1 = wx.Button(self.tbnEntrada, wx.ID_ANY, "ENTRADADA")
        self.button_1.SetBackgroundColour(wx.Colour(50, 153, 204))
        sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.tbnEntrada, wx.ID_ANY, "SALIR")
        self.btnSalir.SetMinSize((89, 23))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 0, 0))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tbnEntrada.SetSizer(sizer_1)

        self.Layout()

        self.button_1.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()
        if nombre == "yurem" and clave == "123":
            print(f"bienvenido, {nombre}! Acceso autorisado.")

            v2= ventana2(self)

            v2.Show()

            self.Hide()
        else:
            print("Acceso denegado, Usuario o clave incorrectos.")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta =wx.MessageDialog(self, "Se cerrara la ventana.\n"\
            "¿Estas seguro que desea salir?","Confirmar salida",style=wx.YES_NO|wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta ==wx.ID_YES:
            print("bye!")
        event.Skip()

# end of class Ventana1

class MyAppcinepluss(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppcinepluss

if __name__ == "__main__":
    app = MyAppcinepluss(0)
    app.MainLoop()
