#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Oct 28 12:21:41 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 413))
        self.SetTitle("Inicio de secion- Cine Pluss")

        self.tbnEntrada = wx.Panel(self, wx.ID_ANY)
        self.tbnEntrada.SetBackgroundColour(wx.Colour(0, 0, 0))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        IbTitulo = wx.StaticText(self.tbnEntrada, wx.ID_ANY, "Bienvenide a cinepluss", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbTitulo.SetMinSize((132, 35))
        IbTitulo.SetForegroundColour(wx.Colour(35, 142, 35))
        IbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbTitulo, 0, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.tbnEntrada, wx.ID_ANY, wx.Bitmap("./logo.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbUsuario = wx.StaticText(self.tbnEntrada, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbUsuario.SetForegroundColour(wx.Colour(35, 142, 35))
        IbUsuario.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(IbUsuario, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.tbnEntrada, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbClave = wx.StaticText(self.tbnEntrada, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbClave.SetMinSize((64, 16))
        IbClave.SetForegroundColour(wx.Colour(35, 142, 35))
        IbClave.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(IbClave, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.tbnEntrada, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_1 = wx.Button(self.tbnEntrada, wx.ID_ANY, "ENTRADADA")
        self.button_1.SetBackgroundColour(wx.Colour(50, 153, 204))
        sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.tbnEntrada, wx.ID_ANY, "SALIR")
        self.btnSalir.SetMinSize((89, 23))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 0, 0))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tbnEntrada.SetSizer(sizer_1)

        self.Layout()

        self.button_1.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()
        if nombre == "yurem" and clave == "123":
            print(f"bienvenido, {nombre}! Acceso autorisado.")
        else:
            print("Acceso denegado, Usuario o clave incorectos.")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta =wx.MessageDialog(self, "Se cerrara la ventana.\n"\
            "¿Estas seguro que desea salir?","Confirmar salida",style=wx.YES_NO|wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta ==wx.ID_YES:
            print("bye!")
            self.Close()
        event.Skip()

# end of class Ventana1

class MyApp(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
