#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Dec  3 18:11:28 2025
#

import wx
from wxglade_v6 import ventanacombos
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class resumentaquilla(wx.Frame):
    def __init__(self,*args,**kwds):
        # begin wxGlade: resumentaquilla.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((505, 376))
        self.SetTitle("Resumen de taquilla")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(234, 24, 62))
        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Resumen de taquilla")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbHora = wx.StaticText(self.panel_1, wx.ID_ANY, "Hora:---")
        lbHora.SetBackgroundColour(wx.Colour(255, 255, 255))
        lbHora.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbHora, 0, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:----")
        lbSala.SetBackgroundColour(wx.Colour(255, 255, 255))
        lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbSala, 0, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        lbboletos = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos:--")
        lbboletos.SetBackgroundColour(wx.Colour(255, 255, 255))
        lbboletos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbboletos, 0, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:---")
        lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        lbSubtotalTaquilla.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbSubtotalTaquilla, 0, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((84, 26))
        self.btnSiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnSiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "cancelar")
        self.btnCancelar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnCancelar.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteventana)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarventa)
        # end wxGlade

    def siguienteventana(self, event):  # wxGlade: resumentaquilla.<event_handler>
        v6=dulceria(self)
        v6.Show()
        event.Skip()

    def cancelarventa(self, event):  # wxGlade: resumentaquilla.<event_handler>
        print("Event handler 'cancelarventa' not implemented!")
        event.Skip()

# end of class resumentaquilla

class dulceria(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: dulceria.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("dulceria")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"¿Deseas comprar productos de dulceria?", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnAceptar = wx.Button(self, wx.ID_ANY, "aceptar")
        self.btnAceptar.SetMinSize((87, 27))
        self.btnAceptar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnAceptar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnAceptar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnAceptar, 0, wx.ALIGN_CENTER, 0)

        self.btnCancelar = wx.Button(self, wx.ID_ANY, "cancelar")
        self.btnCancelar.SetMinSize((87, 27))
        self.btnCancelar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnCancelar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.btnAceptar.Bind(wx.EVT_BUTTON, self.siguientedulceria)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelardulceria)
        # end wxGlade

    def siguientedulceria(self, event):  # wxGlade: dulceria.<event_handler>
        v6=ventanacombos(self)
        v6.Show()
        self.Hide()
        event.Skip()

    def cancelardulceria(self, event):  # wxGlade: dulceria.<event_handler>
        print("Event handler 'cancelardulceria' not implemented!")
        event.Skip()

# end of class dulceria

class MyApp(wx.App):
    def OnInit(self):
        self.frame = resumentaquilla(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
