#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec  4 08:16:03 2025
#

import wx
#from wxglade_v6 import ventanacombos
#from wxglade_v6 import ventanaindividuales 
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana8(wx.Frame):
    def __init__(self, parent, informacion2="", subtotalIndividual=0, informacion="", subtotal1=0, pelicula=""):
        # begin wxGlade: Ventana8.__init__
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((581, 419))
        self.SetTitle("Recibo de compra")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(44, 151, 212))
        
        self.info2=informacion2
        self.subindi=subtotalIndividual
        self.info1=informacion
        self.subcombo=subtotal1
        self.pelicula=pelicula

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Recibo de compra", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((200, 55))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_2.SetMinSize((66, 25))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Duceria")
        label_3.SetMinSize((70, 25))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(6, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula: ")
        self.lbPelicula.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(self.lbPelicula, 0, 0, 0)

        lbpelicula = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.pelicula}")
        lbpelicula.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbpelicula, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_17.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_17, 0, 0, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbHorario.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbHorario, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_3, 1, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos:")
        label_19.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_19, 0, 0, 0)

        lbBoletos = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbBoletos.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbBoletos, 0, 0, 0)

        lbsub = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        lbsub.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(lbsub, 0, 0, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Total:")
        label_21.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_21, 0, 0, 0)

        lbtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbtotal.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbtotal, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.checkcombo = wx.CheckBox(self.panel_1, wx.ID_ANY, "Combo")
        self.checkcombo.SetMaxSize((70, 15))
        grid_sizer_4.Add(self.checkcombo, 0, 0, 0)

        self.checkindi = wx.CheckBox(self.panel_1, wx.ID_ANY, "Individual")
        grid_sizer_4.Add(self.checkindi, 0, 0, 0)

        lb_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Producto:\n")
        lb_21.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lb_21, 0, 0, 0)

        lbproductodulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.info2},{self.info1}")
        lbproductodulceria.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(lbproductodulceria, 0, 0, 0)

        lb_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        lb_8.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lb_8, 0, 0, 0)

        subtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        subtotalDulceria.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(subtotalDulceria, 0, 0, 0)

        self.btnPagar = wx.Button(self.panel_1, wx.ID_ANY, "PAGAR")
        self.btnPagar.SetMinSize((75, 23))
        self.btnPagar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnPagar.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_2.Add(self.btnPagar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "CANCELAR")
        self.btnCancelar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnCancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_2.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnPagar.Bind(wx.EVT_BUTTON, self.pagar_compra)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarcompra)
        # end wxGlade

    def pagar_compra(self, event):  # wxGlade: Ventana8.<event_handler>
        print("Event handler 'pagar_compra' not implemented!")
        event.Skip()

    def cancelarcompra(self, event):  # wxGlade: Ventana8.<event_handler>
        print("Event handler 'cancelarcompra' not implemented!")
        event.Skip()

# end of class Ventana8

class MyApp(wx.App):
    def OnInit(self):
        self.frame = Ventana8(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
