#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Sat Nov 29 00:21:46 2025
#

import wx
#from wxglade_menudepeliculas import ventana3
#from wxglade_v6 import ventanacombos
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((590, 593))
        self.SetTitle("inicio de sesion-CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(30, 120, 204))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "INICIO DE SESION")
        lbTitulo.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Times New Roman"))
        sizer_1.Add(lbTitulo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("IconoUsuario.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((50, 50))
        sizer_1.Add(bitmap_1, 0, 0, 0)

        bmLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bmLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbCine = wx.StaticText(self.panel_1, wx.ID_ANY, "CinePlus")
        lbCine.SetFont(wx.Font(20, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_1.Add(lbCine, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_4 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_4.Add(self.panel_5, 1, wx.EXPAND, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "USUARIO")
        lbUsuario.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lbUsuario, 0, wx.ALIGN_BOTTOM, 0)

        self.panel_6 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_4.Add(self.panel_6, 1, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_3, 1, wx.EXPAND, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, "CLAVE")
        lbClave.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(lbClave, 0, wx.ALIGN_BOTTOM, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_4, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.panel_7 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_2.Add(self.panel_7, 1, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        grid_sizer_2.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_8 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_2.Add(self.panel_8, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnSalir.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnSalir.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 1, "Arial"))
        grid_sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Ingresar")
        self.btnEntrar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnEntrar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnEntrar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 1, "Arial"))
        grid_sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        # end wxGlade

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        pregunta=wx.MessageDialog(self,"Se cerrara la ventana.\n"\
        "¿Estas seguro que deseas salir","Confirmar salida",style=wx.YES_NO| wx.ICON_QUESTION)
        respuesta= pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta== wx.ID_YES:
            print("byeee")
            self.Close()
        event.Skip()
       

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler
        nombre=self.tfUsuario.GetValue()
        clave=self.tfClave.GetValue()
        if nombre == "Estrella" and clave == "123":
            v2=ventana2(self)
            v2.Show()
            self.Hide()
            print(f"¡Bienvenido{nombre} acceso autorizado!")
        else:
            wx.MessageBox("Clave o usuario incorrectos","mensaje",wx.OK |wx.ICON_ERROR)
            print("acceso denegado, usuario o contraseña incorrectos")

        event.Skip()

# end of class ventana1

class ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((498, 371))
        self.SetTitle("Menu principal-CINEPLUS")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(38, 171, 228))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbMenu = wx.StaticText(self.panel_1, wx.ID_ANY, "Menu Principal")
        lbMenu.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbMenu, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(3, 5, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)

        self.bmbtntaquilla = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("secciontaquilla.png", wx.BITMAP_TYPE_ANY))
        self.bmbtntaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.bmbtntaquilla.SetSize(self.bmbtntaquilla.GetBestSize())
        grid_sizer_1.Add(self.bmbtntaquilla, 0, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        self.bmbtndulceria = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("dulceria.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtndulceria.SetSize(self.bmbtndulceria.GetBestSize())
        grid_sizer_1.Add(self.bmbtndulceria, 0, wx.ALIGN_CENTER, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        self.panel_8 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_8, 1, wx.EXPAND, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "\n    Taquilla")
        lbTaquilla.SetMinSize((100, 50))
        lbTaquilla.SetBackgroundColour(wx.Colour(255, 255, 0))
        lbTaquilla.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(lbTaquilla, 0, wx.EXPAND, 0)

        self.panel_6 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)

        lbdulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "    \n   Dulceria")
        lbdulceria.SetMinSize((100, 40))
        lbdulceria.SetBackgroundColour(wx.Colour(255, 255, 0))
        lbdulceria.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(lbdulceria, 0, wx.EXPAND, 0)

        self.panel_7 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_7, 1, wx.EXPAND, 0)

        self.panel_13 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_13, 1, wx.EXPAND, 0)

        self.panel_12 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_12, 1, wx.EXPAND, 0)

        self.panel_9 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_9, 1, wx.EXPAND, 0)

        self.panel_10 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_10, 1, wx.EXPAND, 0)

        self.panel_11 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_11, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.bmbtntaquilla.Bind(wx.EVT_BUTTON, self.ventanaTaquilla)
        self.bmbtndulceria.Bind(wx.EVT_BUTTON, self.ventanaDulceria)
        # end wxGlade

    def ventanaTaquilla(self, event):  # wxGlade: ventana2.<event_handler>
        v3=ventana3(self)
        v3.Show()
        self.Hide()
        
        event.Skip()

    def ventanaDulceria(self, event):  # wxGlade: ventana2.<event_handler>
        v6=ventanacombos(self)
        v6.Show()
        self.Hide()
        event.Skip()

# end of class ventana2
class ventana3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((508, 378))
        self.SetTitle("Menu de peliculas")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(209, 4, 65))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Menú de Películas")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.bmbtnGato = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("Elgatoconbotasultimodeseo.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtnGato.SetSize(self.bmbtnGato.GetBestSize())
        grid_sizer_2.Add(self.bmbtnGato, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "El gato con botas")
        grid_sizer_2.Add(label_2, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "SALA 3")
        grid_sizer_2.Add(label_7, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.bmbtnIT = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("it.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtnIT.SetSize(self.bmbtnIT.GetBestSize())
        grid_sizer_3.Add(self.bmbtnIT, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "IT: ESO")
        grid_sizer_3.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "SALA 2")
        grid_sizer_3.Add(label_6, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.bmbtnChicas = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("chicas.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtnChicas.SetSize(self.bmbtnChicas.GetBestSize())
        grid_sizer_4.Add(self.bmbtnChicas, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas pesadas")
        grid_sizer_4.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "SALA 3")
        grid_sizer_4.Add(label_5, 0, wx.ALIGN_CENTER, 0)

        self.btncancelar = wx.Button(self.panel_1, wx.ID_ANY, "cancelar")
        self.btncancelar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btncancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btncancelar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(self.btncancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.bmbtnGato.Bind(wx.EVT_BUTTON, self.Elgatoconbotas)
        self.bmbtnIT.Bind(wx.EVT_BUTTON, self.iteso)
        self.bmbtnChicas.Bind(wx.EVT_BUTTON, self.Chicaspesadas)
        # end wxGlade
        
    def cancelarventa(self, event):
        v2=ventana2(self,)
        v2.Show()
        self.Hide()
        event.Skip()

    def Elgatoconbotas(self, event):  # wxGlade: ventana3.<event_handler>
        v4=boletosyhorario(self,pelicula1="El gato con botas")
        v4.Show()
        self.Hide()
        event.Skip()

    def iteso(self, event):  # wxGlade: ventana3.<event_handler>
        v4=boletosyhorario(self,pelicula2="IT ESO" )
        self.Hide()
        v4.Show()

        event.Skip()

    def Chicaspesadas(self, event):  # wxGlade: ventana3.<event_handler>
        v4=boletosyhorario(self,pelicula3="Chicas pesadas")
        v4.Show()
        self.Hide()
        event.Skip()

# end of class ventana3

class boletosyhorario(wx.Frame):
    def __init__(self,parent, pelicula1="",pelicula2="",pelicula3=""):
        # begin wxGlade: boletosyhorario.__init__
        super().__init__(parent,style=wx.DEFAULT_FRAME_STYLE)
        self.SetSize((501, 346))
        self.SetTitle("boletos y horarios")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(234, 24, 74))
        
        self.peli=pelicula1
        self.peli2=pelicula2
        self.peli3=pelicula3
        self.subtotalR=0
        self.infotaquilla=""
        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos y horarios")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_3.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Berlin Sans FB"))
        grid_sizer_1.Add(label_3, 0, 0, 0)

        self.lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, f"{pelicula1}{pelicula2}{pelicula3}")
        self.lbPelicula.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(self.lbPelicula, 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios:")
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_2.Add(label_5, 0, wx.EXPAND, 0)

        self.cmbHorarios = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["14:00","17:00","20:00","13:30","16:30","19:30","15:00","18:00","21:00"], style=wx.CB_DROPDOWN)
        grid_sizer_2.Add(self.cmbHorarios, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos $90\nMenores $80")
        label_6.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_2.Add(label_6, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos:")
        label_7.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(label_7, 0, 0, 0)

        self.spAdultos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_3.Add(self.spAdultos, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Niños:")
        label_8.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_4.Add(label_8, 0, 0, 0)

        self.spmenores = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_4.Add(self.spmenores, 0, 0, 0)

        self.btnsiguiente = wx.Button(self.panel_1, wx.ID_ANY, "siguiente")
        self.btnsiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnsiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnsiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnsiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spAdultos.Bind(wx.EVT_SPINCTRL, self.agregarAdultos)
        self.spmenores.Bind(wx.EVT_SPINCTRL, self.agregarninos)
        self.btnsiguiente.Bind(wx.EVT_BUTTON, self.siguienteventana)
        # end wxGlade

    def agregarAdultos(self, event):  # wxGlade: boletosyhorario.<event_handler>
        numero=int(self.spAdultos.GetValue())
        subtotalr=numero*80
        self.subtotalR=self.subtotalR + subtotalr
        self.infotaquilla=self.infotaquilla + f"adultos:{numero} \n"
        #self.subtotalR.SetLabel(self.infotaquilla)
        event.Skip()

    def agregarninos(self, event):  # wxGlade: boletosyhorario.<event_handler>
        numero=int(self.spAdultos.GetValue())
        subtotalr=numero*70
        self.subtotalR=self.subtotalR + subtotalr
        self.infotaquilla=self.infotaquilla+ f"menores:{numero} \n"
        #self.subtotalR.SetLabel(self.infotaquilla)
        event.Skip()

    def siguienteventana(self, event):  # wxGlade: boletosyhorario.<event_handler>
        v5=resumentaquilla(self,peli=self.lbPelicula,
                           horarios=self.cmbHorarios.GetValue(),
                           boletos=self.spmenores.GetValue(),
                           boletosM=self.spAdultos.GetValue(),
                           informacion=self.infotaquilla,
                           subtotal=self.subtotalR,
                           pelicula=self.peli, pelicula2=self.peli2, pelicula3=self.peli3 )
        v5.Show()
        self.Hide()
        event.Skip()
# end of class boletosyhorario

class resumentaquilla(wx.Frame):
    def __init__(self, parent, peli="", horarios=0,boletos=0, boletosM=0, informacion="", subtotal=0, pelicula="", pelicula2="", pelicula3=""):
        # begin wxGlade: resumentaquilla.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((505, 376))
        self.SetTitle("Resumen de taquilla")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        print(f"Datos de la ventana 4 \n informacion: {informacion} \n")
        print(f"subtotal: {subtotal}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(234, 24, 62))
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        
        self.infotaquilla=informacion
        self.pelicula=peli
        self.hora=horarios
        self.boletos= boletos + boletosM
        self.subtotalR=subtotal
        self.sala1=pelicula
        self.sala2=pelicula2
        self.sala3=pelicula3

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Resumen de taquilla")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbHora = wx.StaticText(self.panel_1, wx.ID_ANY, f"Hora:{self.hora}")
        self.lbHora.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbHora.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbHora, 0, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        
        
        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, f"Sala:{self.sala1}{self.sala2}{self.sala3}")
        self.lbSala.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSala, 0, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        self.lbboletos = wx.StaticText(self.panel_1, wx.ID_ANY, f"Boletos: {self.boletos}")
        self.lbboletos.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbboletos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbboletos, 0, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        self.lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: { self.subtotalR}")
        self.lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbSubtotalTaquilla.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotalTaquilla, 0, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((84, 26))
        self.btnSiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnSiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "cancelar")
        self.btnCancelar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnCancelar.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteventana)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarventa)
        # end wxGlade
        
    def limpiarRe(self):
        self.infotaquilla=""
        self.hora="---"
        self.boletos="---"
        self.subtotalR="---"
        self.sala1="---"
        self.sala2="---"
        self.sala3="---"
        self.lbHora="---"
        self.lbboletos="---"
        self.lbSala="---"
        self.lbSubtotalTaquilla="---"
    def limpiarIndividuales (self, event):
        self.limpiarRe()
        event.Skip()


    def siguienteventana(self, event):  # wxGlade: resumentaquilla.<event_handler>
        v6=dulceria(self,perli=self.pelicula)
        v6.Show()
        self.Hide()
        event.Skip()

    def cancelarventa(self, event):  # wxGlade: resumentaquilla.<event_handler>
        v3=ventana3(self)
        v3.Show()
        self.Hide()
        event.Skip()

# end of class resumentaquilla

class dulceria(wx.Dialog):
    def __init__(self, parent, perli=""):
        # begin wxGlade: dulceria.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        #wx.Dialog.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetTitle("dulceria")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        
        self.peliculas=perli

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"¿Deseas comprar productos de dulceria?", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnAceptar = wx.Button(self, wx.ID_ANY, "aceptar")
        self.btnAceptar.SetMinSize((87, 27))
        self.btnAceptar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnAceptar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnAceptar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnAceptar, 0, wx.ALIGN_CENTER, 0)

        self.btnCancelar = wx.Button(self, wx.ID_ANY, "cancelar")
        self.btnCancelar.SetMinSize((87, 27))
        self.btnCancelar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnCancelar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.btnAceptar.Bind(wx.EVT_BUTTON, self.siguientedulceria)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelardulceria)
        # end wxGlade

    def siguientedulceria(self, event):  # wxGlade: dulceria.<event_handler>
        v6=ventanacombos(self, pelicula=self.peliculas)
        v6.Show()
        self.Hide()
        event.Skip()

    def cancelardulceria(self, event):  # wxGlade: dulceria.<event_handler>
        v8=Ventana8(self, pelicula=self.peliculas)
        v8.Show()
        self.Hide()
        event.Skip()

# end of class dulceria
class ventanacombos(wx.Frame):
    def __init__(self, parent, pelicula=""):
        # begin wxGlade: ventanacombos.__init__
        
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((562, 360))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))

        #Variables
        self.infoCombos=""
        self.subtotal1=0
        self.pelicula=pelicula

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "COMBOS")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.FlexGridSizer(4, 7, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("comboclasicos.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("comboCuates.png", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((160, 108))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("combofamiliar.png", wx.BITMAP_TYPE_ANY))
        bitmap_3.SetMinSize((160, 108))
        grid_sizer_1.Add(bitmap_3, 0, 0, 0)

        self.panel_6 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)

        self.panel_11 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_11, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Básico:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetBackgroundColour(wx.Colour(219, 112, 147))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_2, 0, wx.EXPAND, 0)

        self.panel_12 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_12, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo Cuates:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetBackgroundColour(wx.Colour(219, 112, 147))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_3, 0, wx.EXPAND, 0)

        self.panel_13 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_13, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo Familiar:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetBackgroundColour(wx.Colour(219, 112, 147))
        label_4.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_4, 0, wx.EXPAND, 0)

        self.panel_14 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_14, 1, wx.EXPAND, 0)

        self.panel_15 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_15.SetMinSize((20, 46))
        grid_sizer_1.Add(self.panel_15, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 refresco chico (250ml.)\n1 palomitas chicas\n          $75", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetMinSize((160, 46))
        label_5.SetBackgroundColour(wx.Colour(219, 112, 147))
        grid_sizer_1.Add(label_5, 0, 0, 0)

        self.panel_16 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_16.SetMinSize((20, 46))
        grid_sizer_1.Add(self.panel_16, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomiitas medianas y\n2 refrescos medianos\n            $130", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetMinSize((160, 46))
        label_6.SetBackgroundColour(wx.Colour(219, 112, 147))
        grid_sizer_1.Add(label_6, 0, 0, 0)

        self.panel_17 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_17.SetMinSize((20, 46))
        grid_sizer_1.Add(self.panel_17, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas grandes,\n3 refrescos grandes y dulces\n     $230", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_7.SetMinSize((160, 46))
        label_7.SetBackgroundColour(wx.Colour(219, 112, 147))
        grid_sizer_1.Add(label_7, 0, 0, 0)

        self.panel_18 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_18, 1, wx.EXPAND, 0)

        self.panel_7 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_7, 1, wx.EXPAND, 0)

        self.spBasico = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spBasico.SetMinSize((100, 23))
        grid_sizer_1.Add(self.spBasico, 0, wx.ALIGN_CENTER, 0)

        self.panel_8 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_8, 1, wx.EXPAND, 0)

        self.spCuates = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCuates.SetMinSize((100, 23))
        grid_sizer_1.Add(self.spCuates, 0, wx.ALIGN_CENTER, 0)

        self.panel_9 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_9, 1, wx.EXPAND, 0)

        self.spFamiliar = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spFamiliar.SetMinSize((100, 23))
        grid_sizer_1.Add(self.spFamiliar, 0, wx.ALIGN_CENTER, 0)

        self.panel_10 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_10, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad:")
        grid_sizer_2.Add(label_8, 0, 0, 0)

        self.lbCantidad = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        grid_sizer_2.Add(self.lbCantidad, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.btnRegresar = wx.Button(self.panel_1, wx.ID_ANY, "<<Regresar<<")
        self.btnRegresar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnRegresar.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_3.Add(self.btnRegresar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, ">>Siguiente>>")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spBasico.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spCuates.Bind(wx.EVT_SPINCTRL, self.calcularcomboCuates)
        self.spFamiliar.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.btnRegresar.Bind(wx.EVT_BUTTON, self.regresar_a_la_ventana_anterior)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguiente_ventana)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: ventanacombos.<event_handler>
        numero=int(self.spBasico.GetValue())
        subtotalc=numero*75
        self.subtotal1=self.subtotal1 + subtotalc
        self.infoCombos=self.infoCombos + f"{numero}combos basicos \n"
        self.lbCantidad.SetLabel(self.infoCombos)
        event.Skip()

    def calcularcomboCuates(self, event):  # wxGlade: ventanacombos.<event_handler>
        numero=int(self.spBasico.GetValue())
        subtotalC=numero*130
        self.subtotal1=self.subtotal1 + subtotalC
        self.infoCombos=self.infoCombos + f"{numero}combos cuantes \n"
        self.lbCantidad.SetLabel(self.infoCombos)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventanacombos.<event_handler>
        numero=int(self.spBasico.GetValue())
        subtotalC=numero*200
        self.subtotal1=self.subtotal1 + subtotalC
        self.infoCombos=self.infoCombos + f"{numero}combos familiares \n"
        self.lbCantidad.SetLabel(self.infoCombos)
        event.Skip()

    def limpiarC (self):
        self.infoCombos=""
        self.lbCantidad.SetLabel("---")
        self.spBasico.SetValue(0)
        self.spCuates.SetValue(0)
        self.spFamiliar.SetValue(0)
    def limpiarCombos (self, event):
        self.limpiarC()
        event.Skip()

    def regresar_a_la_ventana_anterior(self, event):  # wxGlade: ventanacombos.<event_handler>
        v3=boletosyhorario(self,)
        v3.Show()
        self.Hide
        event.Skip()

    def siguiente_ventana(self, event):  # wxGlade: ventanacombos.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"confirmacion de los combos. \n"
        f"¿estas suguro que desea adquirir?\n \n {self.infoCombos}\n",
        "Combos",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta == wx.ID_YES:
            v7=ventanaindividuales(self, informacion=self.infoCombos, 
                                   subtotalcombos=self.subtotal1,
                                   peliculas=self.pelicula)
            v7.Show()
            self.Hide()
        elif respuesta == wx. ID_NO:
            self.limpiarC()
        event.Skip()

# end of class ventanacombos

class ventanaindividuales(wx.Frame):
    def __init__(self, parent, informacion="", subtotalcombos=0, peliculas=""):
        # begin wxGlade: ventanaindividuales.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((695, 411))
        self.SetTitle("frame_1")
        print(f"Datos de la ventana 6:\n Informacion: {informacion} \n")
        print(f"subtotal: {subtotalcombos}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        
        #variables 
        self.infoIndi=""
        self.subtotal2=0
        self.infoCombos=informacion
        self.subtotalv6=subtotalcombos
        self.peliculo=peliculas

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Individuales")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.FlexGridSizer(3, 7, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.panel_12 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_12.SetMinSize((20, 160))
        grid_sizer_1.Add(self.panel_12, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Refresco.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((200, 160))
        bitmap_2.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        self.panel_13 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_13.SetMinSize((20, 160))
        grid_sizer_1.Add(self.panel_13, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Palomitas.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_3.SetMinSize((200, 160))
        grid_sizer_1.Add(bitmap_3, 0, 0, 0)

        self.panel_14 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_14.SetMinSize((20, 160))
        grid_sizer_1.Add(self.panel_14, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Dulcess.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_4.SetMinSize((200, 160))
        bitmap_4.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_1.Add(bitmap_4, 0, 0, 0)

        self.panel_15 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_15, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Coca-cola,sprite,manzanita", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetMinSize((181, 20))
        label_2.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_2.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_1.Add(label_2, 0, wx.EXPAND, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_3.SetMinSize((200, 20))
        label_3.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_3.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        self.panel_11 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_11, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Gomitas")
        label_4.SetMinSize((200, 20))
        label_4.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        self.panel_10 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_10, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chico: $25")
        label_5.SetMinSize((80, 23))
        label_5.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_2.Add(label_5, 0, wx.EXPAND, 0)

        self.spRefrescoch = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spRefrescoch.SetMinSize((100, 23))
        grid_sizer_2.Add(self.spRefrescoch, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediano: $40")
        label_6.SetMinSize((80, 23))
        label_6.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_2.Add(label_6, 0, 0, 0)

        self.spRefrescomd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spRefrescomd.SetMinSize((100, 23))
        grid_sizer_2.Add(self.spRefrescomd, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grande: $60")
        label_7.SetMinSize((80, 23))
        label_7.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_2.Add(label_7, 0, 0, 0)

        self.spRefrescoG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spRefrescoG.SetMinSize((100, 23))
        grid_sizer_2.Add(self.spRefrescoG, 0, 0, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas: $30")
        label_8.SetMinSize((80, 23))
        label_8.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_8, 0, 0, 0)

        self.spPalomitasch = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasch.SetMinSize((100, 23))
        grid_sizer_3.Add(self.spPalomitasch, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediana: $50")
        label_9.SetMinSize((80, 23))
        label_9.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_9.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_9, 0, 0, 0)

        self.spPalomitasmd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasmd.SetMinSize((100, 23))
        grid_sizer_3.Add(self.spPalomitasmd, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes: $70")
        label_10.SetMinSize((80, 23))
        label_10.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_10, 0, 0, 0)

        self.spPalomitasGr = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasGr.SetMinSize((100, 23))
        grid_sizer_3.Add(self.spPalomitasGr, 0, 0, 0)

        self.panel_6 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas: $10")
        label_11.SetMinSize((80, 23))
        label_11.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_11.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_4.Add(label_11, 0, 0, 0)

        self.spGomitasch = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spGomitasch.SetMinSize((100, 23))
        grid_sizer_4.Add(self.spGomitasch, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediana: $18")
        label_12.SetMinSize((80, 23))
        label_12.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_12.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_4.Add(label_12, 0, 0, 0)

        self.spGomitasmd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spGomitasmd.SetMinSize((100, 23))
        grid_sizer_4.Add(self.spGomitasmd, 0, 0, 0)

        self.panel_7 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_7.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_4.Add(self.panel_7, 1, wx.EXPAND, 0)

        self.panel_8 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_4.Add(self.panel_8, 1, wx.EXPAND, 0)

        self.panel_9 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_9, 1, wx.EXPAND, 0)

        grid_sizer_5 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad:")
        grid_sizer_6.Add(label_13, 0, wx.ALIGN_CENTER, 0)

        self.lbCantidad = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        grid_sizer_6.Add(self.lbCantidad, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, ">>siguiente>>")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(255, 0, 0))
        grid_sizer_5.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnRegresar = wx.Button(self.panel_1, wx.ID_ANY, "<<Regresar<<")
        self.btnRegresar.SetBackgroundColour(wx.Colour(255, 0, 0))
        grid_sizer_5.Add(self.btnRegresar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spRefrescoch.Bind(wx.EVT_SPINCTRL, self.calcularRefrescoChico)
        self.spRefrescomd.Bind(wx.EVT_SPINCTRL, self.calcularRefrescoMdiano)
        self.spRefrescoG.Bind(wx.EVT_SPINCTRL, self.calcularRefrescoGrande)
        self.spPalomitasch.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasChicas)
        self.spPalomitasmd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMedianas)
        self.spPalomitasGr.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasGrandes)
        self.spGomitasch.Bind(wx.EVT_SPINCTRL, self.calcularGomitasChicas)
        self.spGomitasmd.Bind(wx.EVT_SPINCTRL, self.calcularGomitasMedianas)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        self.btnRegresar.Bind(wx.EVT_BUTTON, self.retornar_a_la_ventana_anterior)
        # end wxGlade

    def calcularRefrescoChico(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spRefrescoch.GetValue())
        subtotalI=num*25
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} refrescos chicos \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularRefrescoMdiano(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spRefrescomd.GetValue())
        subtotalI=num*40
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} refrescos medianos\n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularRefrescoGrande(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spRefrescoG.GetValue())
        subtotalI=num*60
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} refrescos grandes \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularPalomitasChicas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spPalomitasch.GetValue())
        subtotalI=num*30
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} palomitas chicas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularPalomitasMedianas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spPalomitasmd.GetValue())
        subtotalI=num*50
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} palomitas medianas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularPalomitasGrandes(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spPalomitasGr.GetValue())
        subtotalI=num*70
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} palomitas grandes \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularGomitasChicas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spGomitasch.GetValue())
        subtotalI=num*10
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} gomitas chicas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularGomitasMedianas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spGomitasmd.GetValue())
        subtotalI=num*18
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} gomitas medianas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def limpiarI (self):
        self.infoIndi=""
        self.lbCantidad.SetLabel("---")
        self.spRefrescoch.SetValue(0)
        self.spRefrescomd.SetValue(0)
        self.spRefrescoG.SetValue(0)
        self.spPalomitasch.SetValue(0)
        self.spPalomitasmd.SetValue(0)
        self.spPalomitasGr.SetValue(0)
        self.spGomitasch.SetValue(0)
        self.spGomitasmd.SetValue(0)
    def limpiarIndividuales (self, event):
        self.limpiarI()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"confirmacion de los individuales. \n"
        f"¿estas suguro que desea adquirir?\n \n {self.infoIndi}\n",
        "individuales",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta == wx.ID_YES:
            v8=Ventana8(self, informacion2=self.infoIndi, 
                        subtotalIndividual=self.subtotal2,
                        informacion=self.infoCombos, 
                        subtotal1=self.subtotalv6,
                        pelicula=self.peliculo)
            v8.Show()
            self.Hide()
        elif respuesta == wx. ID_NO:
            self.limpiarI ()
        event.Skip()

    def retornar_a_la_ventana_anterior(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        v6=ventanacombos(self,)
        v6.Show()
        self.Hide()
        event.Skip()

# end of class ventanaindividuales

class Ventana8(wx.Frame):
    def __init__(self, parent, informacion2="", subtotalIndividual=0, informacion="", subtotal1=0, pelicula=""):
        # begin wxGlade: Ventana8.__init__
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((581, 419))
        self.SetTitle("Recibo de compra")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        
        print(f"Datos de la ventana 7:\n Informacion: {informacion2} \n")
        print(f"subtotal: {subtotalIndividual}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(44, 151, 212))
        
        self.info2=informacion2
        self.subindi=subtotalIndividual + subtotal1
        self.info1=informacion
        self.pelicula=pelicula

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Recibo de compra", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((200, 55))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_2.SetMinSize((66, 25))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Duceria")
        label_3.SetMinSize((70, 25))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(6, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula: ")
        self.lbPelicula.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(self.lbPelicula, 0, 0, 0)

        self.lbpelicula = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.pelicula}")
        self.lbpelicula.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(self.lbpelicula, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_17.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_17, 0, 0, 0)

        self.lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbHorario.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(self.lbHorario, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_3, 1, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos:")
        label_19.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_19, 0, 0, 0)

        self.lbBoletos = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbBoletos.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(self.lbBoletos, 0, 0, 0)

        lbsub = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        lbsub.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(lbsub, 0, 0, 0)

        self.lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(self.lbSubtotalTaquilla, 0, 0, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Total:")
        label_21.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_21, 0, 0, 0)

        self.lbtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbtotal.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(self.lbtotal, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.checkcombo = wx.CheckBox(self.panel_1, wx.ID_ANY, "Combo")
        self.checkcombo.SetMaxSize((70, 15))
        grid_sizer_4.Add(self.checkcombo, 0, 0, 0)

        self.checkindi = wx.CheckBox(self.panel_1, wx.ID_ANY, "Individual")
        grid_sizer_4.Add(self.checkindi, 0, 0, 0)

        lb_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Producto:\n")
        lb_21.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lb_21, 0, 0, 0)

        self.lbproductodulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.info2},{self.info1}")
        self.lbproductodulceria.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(self.lbproductodulceria, 0, 0, 0)

        lb_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        lb_8.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lb_8, 0, 0, 0)

        subtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        subtotalDulceria.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(subtotalDulceria, 0, 0, 0)

        self.btnPagar = wx.Button(self.panel_1, wx.ID_ANY, "PAGAR")
        self.btnPagar.SetMinSize((75, 23))
        self.btnPagar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnPagar.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_2.Add(self.btnPagar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "CANCELAR")
        self.btnCancelar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnCancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_2.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnPagar.Bind(wx.EVT_BUTTON, self.pagar_compra)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarcompra)
        # end wxGlade

    def pagar_compra(self, event):  # wxGlade: Ventana8.<event_handler>
        wx.MessageBox("Compra pagada.", "Finalizar Venta" ,wx.OK | wx.ICON_INFORMATION)
        v2= ventana2(self)
        v2.Show()
        self.Hide()
        event.Skip()

    def cancelarcompra(self, event):  # wxGlade: Ventana8.<event_handler>
        wx.MessageBox("La compra fue cancelada.","Cancelar Venta" ,wx.OK | wx.ICON_INFORMATION)
        wx.Exit()
        event.Skip()

# end of class Ventana8

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
