#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Dec  3 09:29:04 2025
#

import wx
from wxglade_v6 import ventanacombos
from wxglade_recibodecompra import Ventana8
from wxglade_inciosesion import ventana2
#from wxglade_resumentaquilla import resumentaquilla
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((508, 378))
        self.SetTitle("Menu de peliculas")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(209, 4, 65))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Menú de Películas")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.bmbtnGato = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("Elgatoconbotasultimodeseo.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtnGato.SetSize(self.bmbtnGato.GetBestSize())
        grid_sizer_2.Add(self.bmbtnGato, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "El gato con botas")
        grid_sizer_2.Add(label_2, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "SALA 3")
        grid_sizer_2.Add(label_7, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.bmbtnIT = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("it.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtnIT.SetSize(self.bmbtnIT.GetBestSize())
        grid_sizer_3.Add(self.bmbtnIT, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "IT: ESO")
        grid_sizer_3.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "SALA 2")
        grid_sizer_3.Add(label_6, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.bmbtnChicas = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("chicas.jpg", wx.BITMAP_TYPE_ANY))
        self.bmbtnChicas.SetSize(self.bmbtnChicas.GetBestSize())
        grid_sizer_4.Add(self.bmbtnChicas, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas pesadas")
        grid_sizer_4.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "SALA 3")
        grid_sizer_4.Add(label_5, 0, wx.ALIGN_CENTER, 0)

        self.btncancelar = wx.Button(self.panel_1, wx.ID_ANY, "cancelar")
        self.btncancelar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btncancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btncancelar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(self.btncancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.bmbtnGato.Bind(wx.EVT_BUTTON, self.Elgatoconbotas)
        self.bmbtnIT.Bind(wx.EVT_BUTTON, self.iteso)
        self.bmbtnChicas.Bind(wx.EVT_BUTTON, self.Chicaspesadas)
        # end wxGlade
        
    def cancelarventa(self, event):
        v2=ventana2(self,)
        v2.Show()
        self.Hide()
        event.Skip()

    def Elgatoconbotas(self, event):  # wxGlade: ventana3.<event_handler>
        v4=boletosyhorario(self,pelicula1="El gato con botas")
        v4.Show()
        self.Hide()
        event.Skip()

    def iteso(self, event):  # wxGlade: ventana3.<event_handler>
        v4=boletosyhorario(self,pelicula2="IT ESO" )
        self.Hide()
        v4.Show()

        event.Skip()

    def Chicaspesadas(self, event):  # wxGlade: ventana3.<event_handler>
        v4=boletosyhorario(self,pelicula3="Chicas pesadas")
        v4.Show()
        self.Hide()
        event.Skip()

# end of class ventana3

class boletosyhorario(wx.Frame):
    def __init__(self,parent, pelicula1="",pelicula2="",pelicula3=""):
        # begin wxGlade: boletosyhorario.__init__
        super().__init__(parent,style=wx.DEFAULT_FRAME_STYLE)
        self.SetSize((501, 346))
        self.SetTitle("boletos y horarios")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(234, 24, 74))
        
        self.peli=pelicula1
        self.peli2=pelicula2
        self.peli3=pelicula3
        self.subtotalR=0
        self.infotaquilla=""
        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos y horarios")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_3.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Berlin Sans FB"))
        grid_sizer_1.Add(label_3, 0, 0, 0)

        self.lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, f"{pelicula1}{pelicula2}{pelicula3}")
        self.lbPelicula.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(self.lbPelicula, 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios:")
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_2.Add(label_5, 0, wx.EXPAND, 0)

        self.cmbHorarios = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["14:00","17:00","20:00","13:30","16:30","19:30","15:00","18:00","21:00"], style=wx.CB_DROPDOWN)
        grid_sizer_2.Add(self.cmbHorarios, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos $90\nMenores $80")
        label_6.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_2.Add(label_6, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos:")
        label_7.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(label_7, 0, 0, 0)

        self.spAdultos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_3.Add(self.spAdultos, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Niños:")
        label_8.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_4.Add(label_8, 0, 0, 0)

        self.spmenores = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_4.Add(self.spmenores, 0, 0, 0)

        self.btnsiguiente = wx.Button(self.panel_1, wx.ID_ANY, "siguiente")
        self.btnsiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnsiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnsiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnsiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spAdultos.Bind(wx.EVT_SPINCTRL, self.agregarAdultos)
        self.spmenores.Bind(wx.EVT_SPINCTRL, self.agregarninos)
        self.btnsiguiente.Bind(wx.EVT_BUTTON, self.siguienteventana)
        # end wxGlade

    def agregarAdultos(self, event):  # wxGlade: boletosyhorario.<event_handler>
        numero=int(self.spAdultos.GetValue())
        subtotalr=numero*80
        self.subtotalR=self.subtotalR + subtotalr
        self.infotaquilla=self.infotaquilla + f"adultos:{numero} \n"
        #self.subtotalR.SetLabel(self.infotaquilla)
        event.Skip()

    def agregarninos(self, event):  # wxGlade: boletosyhorario.<event_handler>
        numero=int(self.spAdultos.GetValue())
        subtotalr=numero*70
        self.subtotalR=self.subtotalR + subtotalr
        self.infotaquilla=self.infotaquilla+ f"menores:{numero} \n"
        #self.subtotalR.SetLabel(self.infotaquilla)
        event.Skip()

    def siguienteventana(self, event):  # wxGlade: boletosyhorario.<event_handler>
        v5=resumentaquilla(self,peli=self.lbPelicula.Getvalue(),
                           horarios=self.cmbHorarios.GetValue(),
                           boletos=self.spmenores.GetValue(),
                           boletosM=self.spAdultos.GetValue(),
                           informacion=self.infotaquilla,
                           subtotal=self.subtotalR,
                           pelicula=self.peli, pelicula2=self.peli2, pelicula3=self.peli3 )
        v5.Show()
        self.Hide()
        event.Skip()
# end of class boletosyhorario

class resumentaquilla(wx.Frame):
    def __init__(self, parent, peli="", horarios=0,boletos=0, boletosM=0, informacion="", subtotal=0, pelicula="", pelicula2="", pelicula3=""):
        # begin wxGlade: resumentaquilla.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((505, 376))
        self.SetTitle("Resumen de taquilla")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        print(f"Datos de la ventana 4 \n informacion: {informacion} \n")
        print(f"subtotal: {subtotal}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(234, 24, 62))
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        
        self.infotaquilla=informacion
        self.pelicula=peli
        self.hora=horarios
        self.boletos= boletos + boletosM
        self.subtotalR=subtotal
        self.sala1=pelicula
        self.sala2=pelicula2
        self.sala3=pelicula3

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Resumen de taquilla")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbHora = wx.StaticText(self.panel_1, wx.ID_ANY, f"Hora:{self.hora}")
        self.lbHora.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbHora.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbHora, 0, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        
        
        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, f"Sala:{self.sala1}{self.sala2}{self.sala3}")
        self.lbSala.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSala, 0, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        self.lbboletos = wx.StaticText(self.panel_1, wx.ID_ANY, f"Boletos: {self.boletos}")
        self.lbboletos.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbboletos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbboletos, 0, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        self.lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: { self.subtotalR}")
        self.lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbSubtotalTaquilla.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotalTaquilla, 0, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((84, 26))
        self.btnSiguiente.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnSiguiente.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "cancelar")
        self.btnCancelar.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        self.btnCancelar.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteventana)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarventa)
        # end wxGlade
        
    def limpiarRe(self):
        self.infotaquilla=""
        self.hora="---"
        self.boletos="---"
        self.subtotalR="---"
        self.sala1="---"
        self.sala2="---"
        self.sala3="---"
        self.lbHora="---"
        self.lbboletos="---"
        self.lbSala="---"
        self.lbSubtotalTaquilla="---"
    def limpiarIndividuales (self, event):
        self.limpiarRe()
        event.Skip()


    def siguienteventana(self, event):  # wxGlade: resumentaquilla.<event_handler>
        v6=dulceria(self,perli=self.pelicula)
        v6.Show()
        self.Hide()
        event.Skip()

    def cancelarventa(self, event):  # wxGlade: resumentaquilla.<event_handler>
        v3=ventana3(self)
        v3.Show()
        self.Hide()
        event.Skip()

# end of class resumentaquilla

class dulceria(wx.Dialog):
    def __init__(self, parent, perli=""):
        # begin wxGlade: dulceria.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        #wx.Dialog.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetTitle("dulceria")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        
        self.peliculas=perli

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"¿Deseas comprar productos de dulceria?", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnAceptar = wx.Button(self, wx.ID_ANY, "aceptar")
        self.btnAceptar.SetMinSize((87, 27))
        self.btnAceptar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnAceptar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnAceptar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnAceptar, 0, wx.ALIGN_CENTER, 0)

        self.btnCancelar = wx.Button(self, wx.ID_ANY, "cancelar")
        self.btnCancelar.SetMinSize((87, 27))
        self.btnCancelar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnCancelar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnCancelar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.btnAceptar.Bind(wx.EVT_BUTTON, self.siguientedulceria)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelardulceria)
        # end wxGlade

    def siguientedulceria(self, event):  # wxGlade: dulceria.<event_handler>
        v6=ventanacombos(self, pelicula=self.peliculas)
        v6.Show()
        self.Hide()
        event.Skip()

    def cancelardulceria(self, event):  # wxGlade: dulceria.<event_handler>
        v8=Ventana8(self, pelicula=self.peliculas)
        v8.Show()
        self.Hide()
        event.Skip()

# end of class dulceria
class MyApp(wx.App):
    def OnInit(self):
        self.frame = ventana3(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
