#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Dec  2 07:43:30 2025
#

import wx
#from wxglade_menudepeliculas import boletosyhorario
from wxglade_recibodecompra import Ventana8
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventanacombos(wx.Frame):
    def __init__(self, parent, pelicula=""):
        # begin wxGlade: ventanacombos.__init__
        
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((562, 360))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))

        #Variables
        self.infoCombos=""
        self.subtotal1=0
        self.pelicula=pelicula

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "COMBOS")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.FlexGridSizer(4, 7, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./comboclasicos.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./comboCuates.png", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((160, 108))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combofamiliar.png", wx.BITMAP_TYPE_ANY))
        bitmap_3.SetMinSize((160, 108))
        grid_sizer_1.Add(bitmap_3, 0, 0, 0)

        self.panel_6 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)

        self.panel_11 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_11, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Básico:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetBackgroundColour(wx.Colour(219, 112, 147))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_2, 0, wx.EXPAND, 0)

        self.panel_12 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_12, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo Cuates:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetBackgroundColour(wx.Colour(219, 112, 147))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_3, 0, wx.EXPAND, 0)

        self.panel_13 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_13, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo Familiar:", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetBackgroundColour(wx.Colour(219, 112, 147))
        label_4.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_4, 0, wx.EXPAND, 0)

        self.panel_14 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_14, 1, wx.EXPAND, 0)

        self.panel_15 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_15.SetMinSize((20, 46))
        grid_sizer_1.Add(self.panel_15, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 refresco chico (250ml.)\n1 palomitas chicas\n          $75", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetMinSize((160, 46))
        label_5.SetBackgroundColour(wx.Colour(219, 112, 147))
        grid_sizer_1.Add(label_5, 0, 0, 0)

        self.panel_16 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_16.SetMinSize((20, 46))
        grid_sizer_1.Add(self.panel_16, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomiitas medianas y\n2 refrescos medianos\n            $130", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetMinSize((160, 46))
        label_6.SetBackgroundColour(wx.Colour(219, 112, 147))
        grid_sizer_1.Add(label_6, 0, 0, 0)

        self.panel_17 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_17.SetMinSize((20, 46))
        grid_sizer_1.Add(self.panel_17, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas grandes,\n3 refrescos grandes y dulces\n     $230", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_7.SetMinSize((160, 46))
        label_7.SetBackgroundColour(wx.Colour(219, 112, 147))
        grid_sizer_1.Add(label_7, 0, 0, 0)

        self.panel_18 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_18, 1, wx.EXPAND, 0)

        self.panel_7 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_7, 1, wx.EXPAND, 0)

        self.spBasico = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spBasico.SetMinSize((100, 23))
        grid_sizer_1.Add(self.spBasico, 0, wx.ALIGN_CENTER, 0)

        self.panel_8 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_8, 1, wx.EXPAND, 0)

        self.spCuates = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spCuates.SetMinSize((100, 23))
        grid_sizer_1.Add(self.spCuates, 0, wx.ALIGN_CENTER, 0)

        self.panel_9 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_9, 1, wx.EXPAND, 0)

        self.spFamiliar = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spFamiliar.SetMinSize((100, 23))
        grid_sizer_1.Add(self.spFamiliar, 0, wx.ALIGN_CENTER, 0)

        self.panel_10 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_10, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad:")
        grid_sizer_2.Add(label_8, 0, 0, 0)

        self.lbCantidad = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        grid_sizer_2.Add(self.lbCantidad, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.btnRegresar = wx.Button(self.panel_1, wx.ID_ANY, "<<Regresar<<")
        self.btnRegresar.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnRegresar.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_3.Add(self.btnRegresar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, ">>Siguiente>>")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spBasico.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spCuates.Bind(wx.EVT_SPINCTRL, self.calcularcomboCuates)
        self.spFamiliar.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.btnRegresar.Bind(wx.EVT_BUTTON, self.regresar_a_la_ventana_anterior)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguiente_ventana)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: ventanacombos.<event_handler>
        numero=int(self.spBasico.GetValue())
        subtotalc=numero*75
        self.subtotal1=self.subtotal1 + subtotalc
        self.infoCombos=self.infoCombos + f"{numero}combos basicos \n"
        self.lbCantidad.SetLabel(self.infoCombos)
        event.Skip()

    def calcularcomboCuates(self, event):  # wxGlade: ventanacombos.<event_handler>
        numero=int(self.spBasico.GetValue())
        subtotalC=numero*130
        self.subtotal1=self.subtotal1 + subtotalC
        self.infoCombos=self.infoCombos + f"{numero}combos cuantes \n"
        self.lbCantidad.SetLabel(self.infoCombos)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventanacombos.<event_handler>
        numero=int(self.spBasico.GetValue())
        subtotalC=numero*200
        self.subtotal1=self.subtotal1 + subtotalC
        self.infoCombos=self.infoCombos + f"{numero}combos familiares \n"
        self.lbCantidad.SetLabel(self.infoCombos)
        event.Skip()

    def limpiarC (self):
        self.infoCombos=""
        self.lbCantidad.SetLabel("---")
        self.spBasico.SetValue(0)
        self.spCuates.SetValue(0)
        self.spFamiliar.SetValue(0)
    def limpiarCombos (self, event):
        self.limpiarC()
        event.Skip()

    def regresar_a_la_ventana_anterior(self, event):  # wxGlade: ventanacombos.<event_handler>
        v3=boletosyhorario(self,)
        v3.Show()
        self.Hide
        event.Skip()

    def siguiente_ventana(self, event):  # wxGlade: ventanacombos.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"confirmacion de los combos. \n"
        f"¿estas suguro que desea adquirir?\n \n {self.infoCombos}\n",
        "Combos",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta == wx.ID_YES:
            v7=ventanaindividuales(self, informacion=self.infoCombos, 
                                   subtotalcombos=self.subtotal1,
                                   peliculas=self.pelicula)
            v7.Show()
            self.Hide()
        elif respuesta == wx. ID_NO:
            self.limpiarC()
        event.Skip()

# end of class ventanacombos

class ventanaindividuales(wx.Frame):
    def __init__(self, parent, informacion="", subtotalcombos=0, peliculas=""):
        # begin wxGlade: ventanaindividuales.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((695, 411))
        self.SetTitle("frame_1")
        print(f"Datos de la ventana 6:\n Informacion: {informacion} \n")
        print(f"subtotal: {subtotalcombos}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        
        #variables 
        self.infoIndi=""
        self.subtotal2=0
        self.infoCombos=informacion
        self.subtotalv6=subtotalcombos
        self.peliculo=peliculas

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Individuales")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.FlexGridSizer(3, 7, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.panel_12 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_12.SetMinSize((20, 160))
        grid_sizer_1.Add(self.panel_12, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Refresco.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((200, 160))
        bitmap_2.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        self.panel_13 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_13.SetMinSize((20, 160))
        grid_sizer_1.Add(self.panel_13, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Palomitas.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_3.SetMinSize((200, 160))
        grid_sizer_1.Add(bitmap_3, 0, 0, 0)

        self.panel_14 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_14.SetMinSize((20, 160))
        grid_sizer_1.Add(self.panel_14, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Dulcess.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_4.SetMinSize((200, 160))
        bitmap_4.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_1.Add(bitmap_4, 0, 0, 0)

        self.panel_15 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_15, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Coca-cola,sprite,manzanita", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetMinSize((181, 20))
        label_2.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_2.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_1.Add(label_2, 0, wx.EXPAND, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_3.SetMinSize((200, 20))
        label_3.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_3.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        self.panel_11 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_11, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Gomitas")
        label_4.SetMinSize((200, 20))
        label_4.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        self.panel_10 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_10, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chico: $25")
        label_5.SetMinSize((80, 23))
        label_5.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_2.Add(label_5, 0, wx.EXPAND, 0)

        self.spRefrescoch = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spRefrescoch.SetMinSize((100, 23))
        grid_sizer_2.Add(self.spRefrescoch, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediano: $40")
        label_6.SetMinSize((80, 23))
        label_6.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_2.Add(label_6, 0, 0, 0)

        self.spRefrescomd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spRefrescomd.SetMinSize((100, 23))
        grid_sizer_2.Add(self.spRefrescomd, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grande: $60")
        label_7.SetMinSize((80, 23))
        label_7.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_2.Add(label_7, 0, 0, 0)

        self.spRefrescoG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spRefrescoG.SetMinSize((100, 23))
        grid_sizer_2.Add(self.spRefrescoG, 0, 0, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas: $30")
        label_8.SetMinSize((80, 23))
        label_8.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_8, 0, 0, 0)

        self.spPalomitasch = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasch.SetMinSize((100, 23))
        grid_sizer_3.Add(self.spPalomitasch, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediana: $50")
        label_9.SetMinSize((80, 23))
        label_9.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_9.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_9, 0, 0, 0)

        self.spPalomitasmd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasmd.SetMinSize((100, 23))
        grid_sizer_3.Add(self.spPalomitasmd, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes: $70")
        label_10.SetMinSize((80, 23))
        label_10.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_10, 0, 0, 0)

        self.spPalomitasGr = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasGr.SetMinSize((100, 23))
        grid_sizer_3.Add(self.spPalomitasGr, 0, 0, 0)

        self.panel_6 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas: $10")
        label_11.SetMinSize((80, 23))
        label_11.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_11.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_4.Add(label_11, 0, 0, 0)

        self.spGomitasch = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spGomitasch.SetMinSize((100, 23))
        grid_sizer_4.Add(self.spGomitasch, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediana: $18")
        label_12.SetMinSize((80, 23))
        label_12.SetBackgroundColour(wx.Colour(50, 153, 204))
        label_12.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_4.Add(label_12, 0, 0, 0)

        self.spGomitasmd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spGomitasmd.SetMinSize((100, 23))
        grid_sizer_4.Add(self.spGomitasmd, 0, 0, 0)

        self.panel_7 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_7.SetBackgroundColour(wx.Colour(50, 153, 204))
        grid_sizer_4.Add(self.panel_7, 1, wx.EXPAND, 0)

        self.panel_8 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_4.Add(self.panel_8, 1, wx.EXPAND, 0)

        self.panel_9 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_9, 1, wx.EXPAND, 0)

        grid_sizer_5 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad:")
        grid_sizer_6.Add(label_13, 0, wx.ALIGN_CENTER, 0)

        self.lbCantidad = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        grid_sizer_6.Add(self.lbCantidad, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, ">>siguiente>>")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(255, 0, 0))
        grid_sizer_5.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.btnRegresar = wx.Button(self.panel_1, wx.ID_ANY, "<<Regresar<<")
        self.btnRegresar.SetBackgroundColour(wx.Colour(255, 0, 0))
        grid_sizer_5.Add(self.btnRegresar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spRefrescoch.Bind(wx.EVT_SPINCTRL, self.calcularRefrescoChico)
        self.spRefrescomd.Bind(wx.EVT_SPINCTRL, self.calcularRefrescoMdiano)
        self.spRefrescoG.Bind(wx.EVT_SPINCTRL, self.calcularRefrescoGrande)
        self.spPalomitasch.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasChicas)
        self.spPalomitasmd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMedianas)
        self.spPalomitasGr.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasGrandes)
        self.spGomitasch.Bind(wx.EVT_SPINCTRL, self.calcularGomitasChicas)
        self.spGomitasmd.Bind(wx.EVT_SPINCTRL, self.calcularGomitasMedianas)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        self.btnRegresar.Bind(wx.EVT_BUTTON, self.retornar_a_la_ventana_anterior)
        # end wxGlade

    def calcularRefrescoChico(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spRefrescoch.GetValue())
        subtotalI=num*25
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} refrescos chicos \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularRefrescoMdiano(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spRefrescomd.GetValue())
        subtotalI=num*40
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} refrescos medianos\n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularRefrescoGrande(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spRefrescoG.GetValue())
        subtotalI=num*60
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} refrescos grandes \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularPalomitasChicas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spPalomitasch.GetValue())
        subtotalI=num*30
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} palomitas chicas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularPalomitasMedianas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spPalomitasmd.GetValue())
        subtotalI=num*50
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} palomitas medianas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularPalomitasGrandes(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spPalomitasGr.GetValue())
        subtotalI=num*70
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} palomitas grandes \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularGomitasChicas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spGomitasch.GetValue())
        subtotalI=num*10
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} gomitas chicas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def calcularGomitasMedianas(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        num=int(self.spGomitasmd.GetValue())
        subtotalI=num*18
        self.subtotal2=self.subtotal2 + subtotalI
        self.infoIndi=self.infoIndi + f"{num} gomitas medianas \n"
        self.lbCantidad.SetLabel(self.infoIndi)
        event.Skip()

    def limpiarI (self):
        self.infoIndi=""
        self.lbCantidad.SetLabel("---")
        self.spRefrescoch.SetValue(0)
        self.spRefrescomd.SetValue(0)
        self.spRefrescoG.SetValue(0)
        self.spPalomitasch.SetValue(0)
        self.spPalomitasmd.SetValue(0)
        self.spPalomitasGr.SetValue(0)
        self.spGomitasch.SetValue(0)
        self.spGomitasmd.SetValue(0)
    def limpiarIndividuales (self, event):
        self.limpiarI()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"confirmacion de los individuales. \n"
        f"¿estas suguro que desea adquirir?\n \n {self.infoIndi}\n",
        "individuales",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta == wx.ID_YES:
            v8=Ventana8(self, informacion2=self.infoIndi, subtotalIndividual=self.subtotal2,
                        informacion=self.infoCombos, 
                        subtotal1=self.subtotalv6,
                        pelicula=self.peliculo)
            v8.Show()
            self.Hide()
        elif respuesta == wx. ID_NO:
            self.limpiarI ()
        event.Skip()

    def retornar_a_la_ventana_anterior(self, event):  # wxGlade: ventanaindividuales.<event_handler>
        v6=ventanacombos(self,)
        v6.Show()
        self.Hide()
        event.Skip()

# end of class ventanaindividuales

class Ventana8(wx.Frame):
    def __init__(self, parent, informacion2="", subtotalIndividual=0, informacion="", subtotal1=0, pelicula=""):
        # begin wxGlade: Ventana8.__init__
        super().__init__(parent,style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((581, 419))
        self.SetTitle("Recibo de compra")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logocine.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(44, 151, 212))
        
        self.info2=informacion2
        self.subindi=subtotalIndividual
        self.info1=informacion
        self.subcombo=subtotal1
        self.pelicula=pelicula

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Recibo de compra", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((200, 55))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_2.SetMinSize((66, 25))
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Duceria")
        label_3.SetMinSize((70, 25))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Small"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(6, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula: ")
        self.lbPelicula.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(self.lbPelicula, 0, 0, 0)

        lbpelicula = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.pelicula}")
        lbpelicula.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbpelicula, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_17.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_17, 0, 0, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbHorario.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbHorario, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_3, 1, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos:")
        label_19.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_19, 0, 0, 0)

        lbBoletos = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbBoletos.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbBoletos, 0, 0, 0)

        lbsub = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        lbsub.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(lbsub, 0, 0, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Total:")
        label_21.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_21, 0, 0, 0)

        lbtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbtotal.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_3.Add(lbtotal, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.checkcombo = wx.CheckBox(self.panel_1, wx.ID_ANY, "Combo")
        self.checkcombo.SetMaxSize((70, 15))
        grid_sizer_4.Add(self.checkcombo, 0, 0, 0)

        self.checkindi = wx.CheckBox(self.panel_1, wx.ID_ANY, "Individual")
        grid_sizer_4.Add(self.checkindi, 0, 0, 0)

        lb_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Producto:\n")
        lb_21.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lb_21, 0, 0, 0)

        lbproductodulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.info2},{self.info1}")
        lbproductodulceria.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(lbproductodulceria, 0, 0, 0)

        lb_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        lb_8.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lb_8, 0, 0, 0)

        subtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        subtotalDulceria.SetBackgroundColour(wx.Colour(255, 255, 255))
        grid_sizer_4.Add(subtotalDulceria, 0, 0, 0)

        self.btnPagar = wx.Button(self.panel_1, wx.ID_ANY, "PAGAR")
        self.btnPagar.SetMinSize((75, 23))
        self.btnPagar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnPagar.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_2.Add(self.btnPagar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "CANCELAR")
        self.btnCancelar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnCancelar.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_2.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnPagar.Bind(wx.EVT_BUTTON, self.pagar_compra)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarcompra)
        # end wxGlade

    def pagar_compra(self, event):  # wxGlade: Ventana8.<event_handler>
        print("Event handler 'pagar_compra' not implemented!")
        event.Skip()

    def cancelarcompra(self, event):  # wxGlade: Ventana8.<event_handler>
        print("Event handler 'cancelarcompra' not implemented!")
        event.Skip()

# end of class Ventana8

class MyApp(wx.App):
    def OnInit(self):
        self.frame = ventanacombos (None, wx.ID_ANY,"")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True
#self.frame = ventanacombos(None, wx.ID_ANY, "")
# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
